import Head from "next/head"
import { BsFillMoonStarsFill } from "react-icons/bs"
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai"
import Image from "next/image"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Angel Barbosa Portfolio</title>
        <meta name="description" content="Generated by creat" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Angel Barbosa</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Angel Barbosa
            </h2>
            <h3 className="text-2xl py-2">Developer and designer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. A fugiat
              soluta corporis quod quisquam quo sunt earum reiciendis rem
              explicabo eaque consequatur quasi vitae, perferendis temporibus,
              excepturi repellendus ipsum. Asperiores?
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className=""></div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">insert text here later</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui,
              necessitatibus. Inventore voluptatem impedit officiis alias nam,
              saepe rem magni <span className="text-teal-500">word</span>{" "}
              lksdlkdjfkldjfkld <span className="text-teal-500">word</span>{" "}
              jsndj
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui,
              necessitatibus. Inventore voluptatem impedit officiis alias nam,
              saepe rem magn
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">nice designs</h3>
              <p className="py-2">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam
                obcaecati
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">nice designs</h3>
              <p className="py-2">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam
                obcaecati
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">nice designs</h3>
              <p className="py-2">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam
                obcaecati
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
            </div>
          </div>
        </section>
        <section>
          <div></div>
        </section>
      </main>
    </div>
  )
}
